image: docker:stable


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed cetificate

stages:
  - build
  - test
  - release

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose -v
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567
  - echo $CONTAINER_TEST_IMAGE
  - echo $CONTAINER_RELEASE_IMAGE

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker-compose up
    - docker-compose logs task_test
  after_script:
    - echo "Stoping all containers"
#    - docker stop fms mongo osm task_test
    - docker stop $(docker ps -aq)

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
