image: docker:stable


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed cetificate

stages:
  - build
  - test
  - release

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose -v
  - apk add --no-cache git
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567
  - echo $CONTAINER_TEST_IMAGE
  - echo $CONTAINER_RELEASE_IMAGE

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

task request:
  before_script:
    - apk add --no-cache mongodb mongodb-tools
    - ls
    - mongoimport --db ropod_ccu_store --collection robot_statuses --type json --file fleet_management/test/config/db/task_allocation/robot_statuses.json --jsonArray
  stage: test
  script:
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from task_test task_test fms
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

elevator workflow:
  stage: test
  script:
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from elevator_test elevator_test elevator fms
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

path planner requests:
  stage: test
  script:
    - docker-compose -f .gitlab/docker-compose.yml up path_planner_test
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

elevator monitor requests:
  stage: test
  script:
    - docker-compose -f .gitlab/docker-compose.yml up elevator_monitor_test
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

ropod monitor requests:
  stage: test
  script:
    - docker-compose -f .gitlab/docker-compose.yml up ropod_monitor_test
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)



release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
