image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed certificate

stages:
  - build
  - unit tests
  - integration tests
  - release

before_script:
  - docker info
  - apk add --no-cache py-pip 
  - pip install -Iv docker-compose==1.23.2
  - docker-compose -v
  - apk add --no-cache git 
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567
  - echo $CONTAINER_TEST_IMAGE

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

query interface:
  stage: integration tests
  script:
    - docker-compose up -d roscore
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from task_test task_test fms robot_1
    - docker-compose logs
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from query_interface_test query_interface_test
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

elevator monitor:
  stage: unit tests
  script:
    - docker-compose up -d roscore
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from elevator_monitor_test elevator_monitor_test fms elevator
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

ropod monitor:
  stage: unit tests
  script:
    - docker-compose -f .gitlab/docker-compose.yml up ropod_monitor_test
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

elevator workflow:
  stage: integration tests
  script:
    - docker-compose up -d roscore
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from elevator_test elevator_test fms elevator
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

path planner requests:
  stage: integration tests
  script:
    - docker-compose -f .gitlab/docker-compose.yml up path_planner_test
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)
  when: always

task request:
  stage: integration tests
  script:
    - docker-compose up -d roscore
    - docker-compose -f .gitlab/docker-compose.yml up --exit-code-from task_test task_test fms robot_1
    - docker-compose logs
  after_script:
    - echo "Stoping all containers"
    - docker stop $(docker ps -aq)

stable image:
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:stable
  stage: release
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - master
  - tags

latest image:
  stage: release
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - develop
