image: docker:stable



services:
  - docker:dind

stages:
  - build


build:
  stage: build
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker info
    - docker-compose -v
    - docker-compose build
  script:
    - docker-compose run test
  tags:
    - docker
