language: python
python:
  - "3.6"

services:
  - docker

stages:
  - build
  - unit tests

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

jobs:
  include:
    - stage: "Build"
      script:
        - docker build -t hbrs-sdp/fms:testbuild .
        - docker save hbrs-sdp/fms:testbuild | gzip > fms_testbuild.tar.gz
      workspaces:
        create:
          name: ws1
          paths:
            - hbrs-sdp/fms:testbuild

    - stage: "Unit Tests"
      name: "resource management test"
      workspaces:
        use: ws1
      script:
        - docker load < fms_testbuild.tar
        - docker run hbrs-sdp/fms:testbuild pytest test/fms/resources/fleet
        - docker run hbrs-sdp/fms:testbuild pytest test/fms/resources/infrastructure
