language: python
python:
  - "3.6"

services:
  - docker

stages:
  - build
  - unit tests

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

jobs:
  include:
    - stage: "Build"
      script:
        - docker build -t ropod-fms .
        - docker push ropod-fms
      name: "Build docker image"

    #    - script:
    #      name: "push docker image"

    - stage: "Unit Tests"
      name: "resource management test#1"
      script: docker run ropod-fms:latest pytest test/fms/resources/fleet

    - script: docker run ropod-fms:latest pytest test/fms/resources/fleet
      name: "resource management test#2"
