language: python
python:
  - "3.6"

services:
  - docker

stages:
  - build
  - unit tests

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

jobs:
  include:
    [
      stage: "Build",
      name: "Build docker image",
      script: docker build -t ropod-fms .,
    ]
#     -stage: "Build"
#      name: "Build docker image"
#      script: docker build -t ropod-fms .

#     -script: docker push ropod-fms
#      name: "push docker image"

#     -stage: "Unit Tests"
#      name: "resource management test#1"
#      image: ropod-fms
#      script: pytest fleet_management/test/fms/resources/fleet

#     -script: pytest fleet_management/test/fms/resources/infrastructure
#      name: "resource management test#1"
#      image: ropod-fms
