language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - CONTAINER_TEST_IMAGE: hbrs-sdp/fms:$TRAVIS_BRANCH

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

stages:
  - build
  - unit tests
  - integration tests
  - task request tests
  - release

jobs:
  include:
    - stage: "build"
      script:
        - docker build -t $CONTAINER_TEST_IMAGE .
        - docker save -o fms_testbuild.tar.gz $CONTAINER_TEST_IMAGE
      workspaces:
        create:
          name: ws1
          paths:
            - fms_testbuild.tar.gz

    - stage: "unit tests"
      name: "coverage"
      workspaces:
        use: ws1
      script:
        - docker load -i fms_testbuild.tar.gz
        - docker run $CONTAINER_TEST_IMAGE pytest --collect-only --cov=fleet_management test/fms
      allow_failures: true

    - stage: "unit tests"
      name: "docs"
      workspaces:
        use: ws1
      before_script:
        - sudo apt-get -y install make gcc
        - pip install sphinx sphinx_rtd_theme
      script:
        - docker load -i fms_testbuild.tar.gz
        - docker run $CONTAINER_TEST_IMAGE /opt/ropod/fms/fleet-management/docs/make html
      allow_failures: true

    - stage: "unit tests"
      name: "resource management test"
      workspaces:
        use: ws1
      script:
        - docker load -i fms_testbuild.tar.gz
        - docker run $CONTAINER_TEST_IMAGE pytest test/fms/resources/fleet
        - docker run $CONTAINER_TEST_IMAGE pytest test/fms/resources/infrastructure

    - stage: "task request tests"
      workspaces:
        use: ws1
      before_script:
        - docker load -i fms_testbuild.tar.gz
        - docker build -t hbrs-sdp/docker-overpass-api:latest https://github.com/ropod-project/docker-overpass-api.git#brsu
      script:
        - docker-compose up -d roscore
        - docker-compose -f .travis/docker-compose.yml up --exit-code-from task_test_1 task_test_1 fms robot_proxy_1 robot_1
        - docker-compose logs
      after_script:
        - docker stop $(docker ps -aq)
      name: "task_test_1"
