language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - CONTAINER_TEST_IMAGE: hbrs-sdp/fms:$TRAVIS_BRANCH

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

stages:
  - build
  - unit tests

jobs:
  include:
    - stage: "Build"
      script:
        - docker build -t $CONTAINER_TEST_IMAGE .
        - docker save -o fms_testbuild.tar.gz $CONTAINER_TEST_IMAGE
      workspaces:
        create:
          name: ws1
          paths:
            - fms_testbuild.tar.gz

    - stage: "Unit Tests"
      name: "resource management test"
      workspaces:
        use: ws1
      script:
        - docker load -i fms_testbuild.tar.gz
        - docker run $CONTAINER_TEST_IMAGE pytest test/fms/resources/fleet
        - docker run $CONTAINER_TEST_IMAGE pytest test/fms/resources/infrastructure
