language: python
python:
  - "3.6"

services:
  - docker

stages:
  - build
  - unit tests

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

jobs:
  include:
    - stage: "Build"
      script:
        - docker build -t hbrs-sdp/fms:testbuild .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push hbrs-sdp/fms:testbuild
      name: "Build docker image"

    - stage: "Unit Tests"
      name: "resource management test"
      script:
        - docker pull hbrs-sdp/fms:testbuild
        - docker run ropod-fms:latest pytest test/fms/resources/fleet
        - docker run ropod-fms:latest pytest test/fms/resources/infrastructure
