language: python
python:
  - "3.6"

services:
  - docker

stages:
  - build
  - unit tests

before_script:
  - docker info
  - pip install -qqq docker-compose==1.23.2
  - docker-compose -v

jobs:
  include:
     -stage: "Build"
      name: "Build"
      script:
        docker build -t ropod-fms .
        docker push ropod-fms
     -stage: "Unit Tests"
      name: "resource management"
      image: ropod-fms
      script:
        pytest fleet_management/test/fms/resources/fleet
        pytest fleet_management/test/fms/resources/infrastructure

