version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"
  fms:
    container_name: fms
    restart: always
    stdin_open: true
    tty: true
    image: git.ropod.org:4567/ropod/ccu/fleet-management:latest
    network_mode: "host"
    depends_on:
      - mongo
    command: ["bash", "-c", "cd /fleet-management/build; ./ccu"]
  task_test:
    image: git.ropod.org:4567/ropod/ccu/fleet-management:latest
    command: ["bash", "-c", "cd /fleet-management/build/test/; ./task_request_test"]
    container_name: fms-test
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - fms
  local_test:
    image: git.ropod.org:4567/ropod/ccu/fleet-management:latest
    container_name: fms-test
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - ./:/fleet-management
    depends_on:
      - mongo
