version: "2"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"

  osm:
    container_name: osm
    image: git.ropod.org:4567/ropod/wm/docker-overpass-api:latest
    ports:
      - "8000:80"

  elevator:
    image: git.ropod.org:4567/ropod/infrastructure/ropod-elevator:latest
    restart: on-failure
    container_name: ropod-elevator
    volumes:
      - /var/logs/ropod-elevator:/opt/ropod/ropod-elevator/logger
      - /tmp:/tmp/
    network_mode: "host"
    working_dir: /opt/ropod/ropod-elevator/bin/
    command: ["./ropod_elevator",  "/opt/ropod/ropod-elevator/examples/config/config_ropod_elevator_sim.json"]
    depends_on:
      - elevator_simulator

  elevator_simulator:
    image: git.ropod.org:4567/ropod/infrastructure/ropod-elevator:simulator
    container_name: simulated-elevator
    network_mode: "host"
    working_dir: /workspace/bin/
    volumes:
      - /tmp/:/tmp/
    command: ["./elevator_simulator"]

  fms:
    build: .
    container_name: fms
    # restart: always
    stdin_open: true
    tty: true
    image: ropod-fms
    network_mode: "host"
    depends_on:
      - mongo
      - osm
    command: ["python3", "ccu.py"]

  task_test:
    image: ropod-fms
    working_dir: /opt/ropod/fleet-management/fleet_management/test/
    command: ["python3", "task_request_test.py"]
    container_name: task-request-test
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - fms
      - osm

  elevator_test:
    image: ropod-fms
    working_dir: /opt/ropod/fleet-management/fleet_management/test/
    command: ["python3", "elevator_request_test.py"]
    container_name: elevator-test
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - fms
      - elevator
      - elevator_simulator

  path_planner_test:
    image: ropod-fms
    working_dir: /opt/ropod/fleet-management/fleet_management/test/
    command: ["python3", "path_planner_test.py"]
    container_name: path-planner-test
    network_mode: "host"
    depends_on:
      - osm
