version: "2"
services:
  fms:
    container_name: fms
    restart: always
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
      - /opt/ropod_common:/opt/ropod_common
    image: ropod-fms:latest
    network_mode: "host"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"

  test:
    image: ropod-fms:latest
    volumes:
      - .:/workspace
      - /opt/ropod_common:/opt/ropod_common
    command: ["bash", "-c", "cd /workspace; rm -rf build ; mkdir build && cd build ; cmake .. && make"]
