ccu_store_db_name: ropod_ccu_store
ropods:
    ropod_001:
        id: ropod_001
    ropod_002:
        id: ropod_002
    ropod_003:
        id: ropod_003
    ropod_004:
        id: ropod_004
    ropod_005:
        id: ropod_005
elevators:
    elevator_1:
        id: 1
message_version: 0.1.0
zyre_group_name: ROPOD
task_manager_zyre_params:
    node_name: task_manager
    groups: [ROPOD]
    message_types: [TASK]
resource_manager_zyre_params:
    node_name: resource_manager
    groups: [ROPOD, ELEVATOR-CONTROL]
    message_types: [ELEVATOR-STATUS, ELEVATOR-STATUS-QUERY, ELEVATOR-CMD, ELEVATOR-CMD-REPLY, ROBOT-CALL-UPDATE, ROBOT-CALL-UPDATE-REPLY]
task_allocator_zyre_params:
    groups: [TASK-ALLOCATION, TASK-MONITORING]
    message_types: [TASK-ANNOUNCEMENT, BID, ALLOCATION, RENEWAL, ACKOWNLEDGEMENT, REAUCTION]
overpass_server: 127.0.0.1:8000  #192.168.92.10:8000
