- ropod_task_data_db_name: ropod_task_data
- ropods:
    - ropod:
        id: ropod_1
    - ropod:
        id: ropod_2
    - ropod:
        id: ropod_3
    - ropod:
        id: ropod_4
    - ropod:
        id: ropod_5
- elevators:
    - elevator:
        id: 1
- message_version: 0.1.0
- zyre_group_name: ROPOD
- task_manager_params:
    node_name: task_manager
    groups: [ROPOD]
    message_types: [TASK]
- resource_manager:
    node_name: resource_manager
    groups: [ROPOD, ELEVATOR-CONTROL]
    message_types: [ELEVATOR-STATUS, ELEVATOR-STATUS-QUERY, ELEVATOR-CMD, ELEVATOR-CMD-REPLY, ROBOT-CALL-UPDATE, ROBOT-CALL-UPDATE-REPLY]